env:
  browser: true
  commonjs: true
  es6: true
extends: 'airbnb-base'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  no-underscore-dangle:
    - off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
